### PR TITLE
Heroku postgres

### PR DESCRIPTION
**Pull request by hiranprk**
Implemented Postgres Database. Details are in the travel-companion repo.

### CODE REVIEW

**Comment by hiranprk** [comment]
you will need to install psycopg2-binary==2.9.9 package (or put in your requirements.txt and do $ pip install -r requirements.txt)

add the following to your .env:
$ DATABASE_URL = "postgres://ua3tdug8ak0qaj:p0eee379e52689cc5c2e9d8eae322d4821bcdf76b9bea3ab81091ed59210b4c9a@cb5ajfjosdpmil.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com:5432/d979dmm0ljttb2"

**Comment by flattumc** [comment]
Nice job on this! I was able to get to the postgres table, create my own itinerary, and open the page following the updated plan-a-trip route (6). 

I was unable to get the chat history to load. I tried this link: http://127.0.0.1:8080//chat-plan-a-trip/1

I also was unable to edit the itinerary after loading up a historical itinerary. http://127.0.0.1:8080//plan-a-trip/1. I tried searching for a new location, group, days, budget and hit 'Get Itinerary', but got an error when doing so. 

I'm also a little confused as to if the Update Itinerary button works as it was in the .md notes, but also the to do section. I tried it out with no success.

**Comment by flattumc** [comment]
One other thing I'm noticing is that the recommendations page no longer populates with itinerary and weather data. 
I've added a comment to fix the web.py in the other PR

**Comment by flattumc** [comment]
I am also having issues with multi digit trip_id's (try trip id 9 vs 10) when loading the plan-a-trip page

**Comment by hiranprk** [comment]
@flattumc 
- the chat-plan-a-trip route is [POST] that's why its not rendering. I'm not able to implement chat history between GPT and user in the chat box yet. So when we route plan-a-trip/<id> [GET], the latest itinerary is shown but the chat box will by empty. All chats are saved in the DB tho.

- the Update Itinerary Button isn't routed yet, it must be routed to /update-plan-a-trip/<trip_id>

**Comment by hiranprk** [comment]
> One other thing I'm noticing is that the recommendations page no longer populates with itinerary and weather data. I've added a comment to fix the web.py in the other PR

I fixed this in the travel companion PR

**Comment by hiranprk** [comment]
> I am also having issues with multi digit trip_id's (try trip id 9 vs 10) when loading the plan-a-trip page

fixed :)

**Comment by nswai983** [comment]
Build currently fails due to issues with importing promptType. 

Here are the logs:
```
2024-08-12T00:03:12.280589+00:00 app[web.1]:   File "/app/service/main.py", line 15, in <module>
2024-08-12T00:03:12.280590+00:00 app[web.1]:     from promptType import promptType
2024-08-12T00:03:12.280590+00:00 app[web.1]: ModuleNotFoundError: No module named 'promptType'
2024-08-12T00:03:12.280732+00:00 app[web.1]: [2024-08-12 00:03:12 +0000] [9] [INFO] Worker exiting (pid: 9)
2024-08-12T00:03:12.308917+00:00 heroku[web.1]: State changed from starting to up
2024-08-12T00:03:12.337063+00:00 app[web.1]: [2024-08-12 00:03:12 +0000] [2] [WARNING] Worker with pid 9 was terminated due to signal 15
2024-08-12T00:03:12.432373+00:00 app[web.1]: [2024-08-12 00:03:12 +0000] [2] [INFO] Shutting down: Master
2024-08-12T00:03:12.432399+00:00 app[web.1]: [2024-08-12 00:03:12 +0000] [2] [INFO] Reason: Worker failed to boot.
2024-08-12T00:03:12.484932+00:00 heroku[web.1]: Process exited with status 3
2024-08-12T00:03:12.504456+00:00 heroku[web.1]: State changed from up to crashed
```

**Review by noazaj — APPROVED** [review]
Approved!

**Pull request merged**
